import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";

export default defineConfig({
  extends: [core],
  ignorePatterns: [...(core.ignorePatterns as string[]), "docs/*.d.ts"],
  rules: {
    "array-type": "off",
    "arrow-body-style": "off",
    "ban-types": "off",
    complexity: "off",
    "consistent-return": "off",
    "consistent-type-definitions": "off",
    "consistent-type-specifier-style": "off",
    curly: "off",
    eqeqeq: "off",
    "filename-case": "off",
    "func-name-matching": "off",
    "func-style": "off",
    "guard-for-in": "off",
    "import-style": "off",
    "max-classes-per-file": "off",
    "no-array-for-each": "off",
    "no-array-sort": "off",
    "no-await-in-loop": "off",
    "no-bitwise": "off",
    "no-empty-function": "off",
    "no-empty-interface": "off",
    "no-empty-object-type": "off",
    "no-eq-null": "off",
    "no-explicit-any": "off",
    "no-immediate-mutation": "off",
    "no-inferrable-types": "off",
    "no-lonely-if": "off",
    "no-namespace": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-non-null-assertion": "off",
    "no-object-as-default-parameter": "off",
    "no-plusplus": "off",
    "no-promise-executor-return": "off",
    "no-redeclare": "off",
    "no-shadow": "off",
    "no-unsafe-argument": "off",
    "no-unsafe-assignment": "off",
    "no-unsafe-call": "off",
    "no-unsafe-function-type": "off",
    "no-unsafe-member-access": "off",
    "no-unsafe-return": "off",
    "no-unsafe-type-assertion": "off",
    "no-use-before-define": "off",
    "no-useless-undefined": "off",
    "numeric-separators-style": "off",
    "one-var": "off",
    "parameter-properties": "off",
    "prefer-at": "off",
    "prefer-destructuring": "off",
    "prefer-dom-node-append": "off",
    "prefer-dom-node-dataset": "off",
    "prefer-export-from": "off",
    "prefer-import-meta-properties": "off",
    "prefer-named-capture-group": "off",
    "prefer-number-coercion": "off",
    "prefer-spread": "off",
    "prefer-template": "off",
    "promise/avoid-new": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "off",
    "promise/prefer-catch": "off",
    "require-await": "off",
    "require-module-specifiers": "off",
    "require-param-description": "off",
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "sort-vars": "off",
    "strict-boolean-expressions": "off",
    "strict-void-return": "off",
    "switch-case-braces": "off",
    "text-encoding-identifier-case": "off",
    "typescript/no-base-to-string": "off",
    "typescript/no-confusing-void-expression": "off",
    "typescript/no-namespace": "off",
    "typescript/no-redundant-type-constituents": "off",
    "typescript/no-unnecessary-type-parameters": "off",
    "typescript/no-unsafe-enum-comparison": "off",
    "typescript/non-nullable-type-assertion-style": "off",
    "typescript/prefer-nullish-coalescing": "off",
    "typescript/promise-function-async": "off",
    "typescript/switch-exhaustiveness-check": "off",
    "typescript/unbound-method": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-lonely-if": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/prefer-number-properties": "off",
    "unicorn/prefer-spread": "off",
    "unicorn/prefer-string-replace-all": "off",
  },
  overrides: [
    {
      files: ["**/index.ts"],
      rules: {
        "no-barrel-file": "off",
      },
    },
    {
      files: ["**/prehydrationScript.template.js"],
      rules: {
        "prefer-const": "off",
        "no-unsafe-assignment": "off",
        "no-unsafe-call": "off",
        "no-unsafe-member-access": "off",
      },
    },
    {
      files: ["**/*.spec.tsx"],
      rules: {
        "no-unused-expressions": "off",
        "no-unused-vars": "off",
      },
    },
  ],
});
