// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/(main)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(main)")>;
      $$route?: undefined;
    },
    {
      path: "/(main)/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(main)/[...404]")>;
      $$route?: undefined;
    },
    {
      path: "/(main)/components";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(main)/components")>;
      $$route?: undefined;
    },
    {
      path: "/(main)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(main)/index")>;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/accordion/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/alert-dialog/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/avatar/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/button/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/checkbox/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/checkbox-group/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/collapsible/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/dialog/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/field/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/fieldset/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/form/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/scroll-area/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/separator/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/slider/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/switch/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/tabs/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/toggle/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/toggle-group/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/tooltip/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/preview-card/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(main)/components/popover/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/(main)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(main)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(main)/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/*404";
          id: "/*404";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(main)/[...404]")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/components";
          id: "/components";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(main)/components")>;
          $$route?: undefined;
          children: readonly [
            {
              path: "/form/";
              id: "/form/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/tabs/";
              id: "/tabs/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/field/";
              id: "/field/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/avatar/";
              id: "/avatar/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/button/";
              id: "/button/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/dialog/";
              id: "/dialog/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/slider/";
              id: "/slider/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/switch/";
              id: "/switch/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/toggle/";
              id: "/toggle/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/tooltip/";
              id: "/tooltip/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/popover/";
              id: "/popover/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/checkbox/";
              id: "/checkbox/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/fieldset/";
              id: "/fieldset/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/accordion/";
              id: "/accordion/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/separator/";
              id: "/separator/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/collapsible/";
              id: "/collapsible/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/scroll-area/";
              id: "/scroll-area/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/alert-dialog/";
              id: "/alert-dialog/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/toggle-group/";
              id: "/toggle-group/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/preview-card/";
              id: "/preview-card/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            },
            {
              path: "/checkbox-group/";
              id: "/checkbox-group/";
              page: true;
              $component: FileRouteLazyRef;
              $$route?: undefined;
              children?: undefined;
            }
          ];
        }
      ];
    }
  ];
}
